---
- name: "GATHER NXOS FACTS PLAYBOOK"
  hosts: "nxos_switches"

  tasks:
    - name: "GATHER NXOS FACTS"
      cisco.nxos.nxos_facts:
        gather_subset: "!interfaces"

    - name: "PRINT FACTS"
      ansible.builtin.debug:
        msg:
          - "OS Version: {{ ansible_net_version }}"
          - "Model: {{ ansible_net_model }}"
...
